plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-batch'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	// https://mvnrepository.com/artifact/org.springframework/spring-web
	implementation 'org.springframework:spring-web:6.2.1'

	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'

	// https://mvnrepository.com/artifact/org.slf4j/slf4j-api
	implementation 'org.slf4j:slf4j-api:2.0.16'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.batch:spring-batch-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// https://mvnrepository.com/artifact/com.h2database/h2
	testImplementation 'com.h2database:h2:2.3.232'
	// https://mvnrepository.com/artifact/org.flywaydb/flyway-core
	testImplementation 'org.flywaydb:flyway-core:11.1.1'
	testImplementation 'junit:junit:4.13.1'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// https://mvnrepository.com/artifact/org.mock-server/mockserver-netty-no-dependencies
	testImplementation 'org.mock-server:mockserver-netty-no-dependencies:5.15.0'
	// https://mvnrepository.com/artifact/org.mock-server/mockserver-client-java-no-dependencies
	implementation 'org.mock-server:mockserver-client-java-no-dependencies:5.15.0'


}

tasks.named('test') {
	useJUnitPlatform()
}
