spring.application.name=delete_products_batchjob

spring.datasource.product.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.product.url=${PRODUCT_SPRING_DATASOURCE_URL}
spring.datasource.product.username=${PRODUCT_MYSQL_USER}
spring.datasource.product.password=${PRODUCT_MYSQL_PASSWORD}
spring.datasource.product.hikari.connectionTimeout=30000
spring.datasource.product.hikari.idleTimeout=600000
spring.datasource.product.hikari.maxLifetime=1800000

spring.datasource.staging.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.staging.url=${STAGING_SPRING_DATASOURCE_URL}
spring.datasource.staging.username=${STAGING_MYSQL_USER}
spring.datasource.staging.password=${STAGING_MYSQL_PASSWORD}
spring.datasource.staging.hikari.connectionTimeout=30000
spring.datasource.staging.hikari.idleTimeout=600000
spring.datasource.staging.hikari.maxLifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=30000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.batch.initialize-schema=ALWAYS
spring.main.allow-bean-definition-overriding=true
